### ISSUE TITLE
What is batch job?

### ISSUE THREAD

**Issue by VikasRana** [andresoviedo/google-drive-ftp-adapter#18]
Sorry but I'm not that much familier with the technicality of this program. Thanks a lot for making it this simple that a person like me is running it successfully and is able to know basic things involved here. 

Here is this thing I would like to know more about sir. I have a config with 5 users. Whenever I try to terminate the console with ctrl+C (in Windows) it prompts me whether to cancel the batch job or not with Y/N options. I do N and it proceeds in closing the console for me. I would like to know what is batch job here? Also is it possible to add new user on same config from which the old instance is running and add that user in that instance without needing to restart the server which we do using start.cmd? If it's not possible and if it is related to batch job or something (just a wild guess) is it possible to not interrupt the current transfer processes upon closing and restarting the server - done to add new user to it?

Thanks a lot. I hope I am making sense here, because I don't know how this works. And thanks a lot again for implementing my requests in such a timely way.

Cheers>

**Comment by andresoviedo** [comment]
Hello body. 

A batch job is a computer program or set of programs processed in batch mode. This means that a sequence of commands to be executed by the operating system is listed in a file (often called a batch file, command file, or shell script) and submitted for execution as a single unit. The opposite of a batch job is interactive processing, in which a user enters individual commands to be processed immediately.
So. When you type Ctrl-c, the process you are stopping is the java process.

Yes. It's possible to add multiple users in the same config file. But in order to add more users the process should be restarted.

About not interrupting the current transfer when restarting the server, I think that's possible to implement.  If you want that to be implemented please open a new ticket.

Kind regards
